### ISSUE TITLE
Does serverless-ngrok-tunnel support serverless v3 and it's new parameters 

### ISSUE THREAD

**Issue by Adi33-cloud** [mitipi/serverless-ngrok-tunnel#11]
I was just wondering if this plugin will support serverless v3 and its new CLI commands and options soon.  more specifically for the `sls offline start --tunnel=true` command https://www.serverless.com/framework/docs/guides/upgrading-v3

**Comment by SSTPIERRE2** [comment]
It says `Detected unrecognized CLI options: "--tunnel".` on my end with serverless v3 and serverless offline v8.8.0

**Comment by abhijeet-toptal** [comment]
@nenadpnc do you plan to fix this error?

**Comment by abhi-at-bitsy** [comment]
any updates?

**Comment by nenadpnc** [comment]
If anyone is willing to submit the PR for this, i'll gladly review/accept it.

**Comment by abhijeet-toptal** [comment]
@nenadpnc here's the PR: https://github.com/mitipi/serverless-ngrok-tunnel/pull/12

**Comment by abhi-at-bitsy** [comment]
@nenadpnc can you please review and merge the PR?

**Comment by abhi-at-bitsy** [comment]
@nenadpnc  any updates?

**Comment by nenadpnc** [comment]
Closed by #12
